feat: raw report stream customer method
Opteo/google-ads-api pull request #248
Opened 2021-04-01 10:28 UTC by WillCooter

2021-04-09 16:26 UTC, Midnight-Conqueror requested changes

2021-04-09 16:26 UTC, Midnight-Conqueror commented on src/customer.spec.ts
> +    // TODO:
Todo?

2021-04-09 16:27 UTC, WillCooter commented on src/customer.spec.ts
> +    // TODO:
oh shite

2021-04-12 12:04 UTC, Midnight-Conqueror approved these changes

2021-04-12 12:22 UTC, kritzware approved these changes
Really good work, all seems ready to me. The documentation you've done for the types/functions & README amends are also really nice.

2021-04-12 16:45 UTC, avermeil commented on README.md
> +Returns the raw stream so that events can be handled manually. This is the recommended method of retrieving data with over 10,000 rows. For more information on Google's stream methods please [consult
Nice work updating the docs to reflect the changes! However, is this 10,000 rows recommendation still true?

2021-04-12 16:56 UTC, avermeil approved these changes
Very nice! Just that one thing about the 10k row limit in the docs and I think this is g2g 🚀

2021-04-13 09:10 UTC, merged